### ISSUE TITLE
errors on regenerating, breaks regeneration, no error information

### ISSUE THREAD

**Issue by brainlid** [kinnetica/jekyll-plugins#31]
## Steps to Reproduce

* Using Jekyll 3.0.1, create a new Jekyll project
```
$ jekyll new test_project
```
* Create ```_plugins``` folder
* Copy in current [sitemap_generator.rb](https://github.com/kinnetica/jekyll-plugins/blob/master/sitemap_generator.rb)
* Copy "sitemap" configuration settings into ```_config.yml``` file (from readme)
* Run ```$ jekyll serve --trace```
* Using a text editor, open the ```about.md``` file. Change nothing. Just save it and see that the file was regenerated. Save the file a second time and see the error.
* Now jekyll regeneration on change is broken. You must restart the ```jekyll serve``` process to see your text changes.

I was unable to figure out anything more about the error. This is my first attempt at debugging a jekyll plugin and it seems quite difficult a process (debugging plugins that-is).

Needless to say, ```--trace``` does not show an error on ```build``` as it happens during regeneration. The ```--trace``` flag doesn't seem helpful in this case. 

## Full Output Example

```
$ jekyll serve --trace
Configuration file: /home/mark/dev/jekyll/testing_debug/_config.yml
            Source: /home/mark/dev/jekyll/testing_debug
       Destination: /home/mark/dev/jekyll/testing_debug/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.522 seconds.
 Auto-regeneration: enabled for '/home/mark/dev/jekyll/testing_debug'
Configuration file: /home/mark/dev/jekyll/testing_debug/_config.yml
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
      Regenerating: 1 file(s) changed at 2015-11-22 19:11:29 ...done in 0.174784221 seconds.
      Regenerating: 1 file(s) changed at 2015-11-22 19:11:31 ...error:
             Error: no implicit conversion of nil into String
             Error: Run jekyll build --trace for more information.
```

**Comment by jsuter** [comment]
The issue looks like it's coming from File.join operating on nil. Try swapping lines 22 and 34 respectively to the following:

`File.join(*[@name].compact)`
`File.join(*[@dir, @name].compact)`

Does that fix the issue?

**Comment by brainlid** [comment]
That fixed it. :+1: Thanks!

**Comment by jsuter** [comment]
:tada:
